### ISSUE TITLE
App icons missing on update to 0.8.3

### ISSUE THREAD

**Issue by Silent-Hunter** [quaap/LaunchTime#83] opened 2018-09-02 15:03 UTC
I have a few of the "Simple" apps installed, Simple Contacts, Simple Calendar, Simple Gallery, and Simple Draw. All four of those apps have had their icons removed entirely, and only those four. I've looked everywhere but I see no way to reset LaunchTime to restore apps or redetect them. They're still on the phone, I can launch them from inside F-Droid.

**Comment by quaap** [comment] 2018-09-02 16:45
Strange,  I use several of those too, and I haven't seen them disappear.  If you go to the search/recent tab, can you search for them?  

LaunchTime scans all apps on each start-up. After that, it listens for apps to be installed and uninstalled.  If you want to force it to scan all apps again, you can restart Launchtime either by restarting the device, or going into app settings and doing a "force stop" on LaunchTime and then clicking the home button.

I'll look around for some other possibilities, too.

**Comment by Silent-Hunter** [comment] 2018-09-02 17:01
I rebooted the phone twice, cleared LaunchTime's cache, and force stopped it and then rebooted the phone again. None of these things helped. Maybe if I reinstall the apps it will help. The apps do not show up in LaunchTime's search area.

**Comment by quaap** [comment] 2018-09-02 17:10
Ok, that should have rescanned.  I'll start debugging.

**Comment by quaap** [comment] 2018-09-02 17:11
Oh, what android version/device do you have?

**Comment by quaap** [comment] 2018-09-02 19:12
Ok, I couldn't reproduce the problem at first, but I think I understand what is happening.  If yours is the same as mine, I bet you changed the app icon color.

First, the workaround:  
Launch the app from F-Droid.
Go into the app's settings -> Customize Colors -> App icon color.
Pick the orange color: #F57C00.
Click Ok.
Click the checkmark at the top.

You'll need to restart LaunchTime (Force Stop would be easiest).

Explanation:  With all the "Simple" apps, you can customize the launcher icon color.  They do this by enabling or disabling different activities in the app, so that a whole different activity will be the default.  Recently I added a check to better weed out disabled apps, but it doesn't play well with how the "Simple" apps work.  I know how to fix it, and it should be fixed in the next version.

**Comment by quaap** [comment] 2018-09-02 19:16
Or uninstall the app, and reinstall.  No restart required.  I'm not sure if this would work if you had clicked "Apply colors to all Simple Apps".

**Comment by Silent-Hunter** [comment] 2018-09-02 19:51
Okay thanks!

**Closed** 2018-09-17 23:42 UTC
